### ISSUE TITLE
todo: Write tests

### ISSUE THREAD

**Issue by peppidesu** [peppidesu/solrunners-site#9]
# Unit tests
- [ ] components
  - [ ] `base_page`
    - [ ] no errors or panics
    - [ ] strategize on arguments
  - [ ] `navbar`
    - [ ] no errors or panics
  - [ ] `spinner`
    - [ ] no errors or panics

# End-to-end tests
- at least 75% coverage in each route that isn't a redirect
